name: openmm
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - attr=2.5.2
  - blinker=1.9.0
  - blosc=1.21.6
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-blosc2=2.22.0
  - ca-certificates=2025.10.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2025.10.5
  - cftime=1.6.4
  - click=8.3.0
  - colorama=0.4.6
  - contourpy=1.3.3
  - cpython=3.13.9
  - cuda-cccl_linux-64=12.9.27
  - cuda-crt-dev_linux-64=12.9.86
  - cuda-crt-tools=12.9.86
  - cuda-cudart=12.9.79
  - cuda-cudart-dev_linux-64=12.9.79
  - cuda-cudart-static_linux-64=12.9.79
  - cuda-cudart_linux-64=12.9.79
  - cuda-cupti=12.9.79
  - cuda-cupti-dev=12.9.79
  - cuda-nvcc-tools=12.9.86
  - cuda-nvrtc=12.9.86
  - cuda-nvtx=12.9.79
  - cuda-nvvm-tools=12.9.86
  - cuda-version=12.9
  - cudnn=9.10.1.4
  - cycler=0.12.1
  - deeptime=0.4.5
  - filelock=3.20.0
  - flask=3.1.2
  - fonttools=4.60.1
  - freetype=2.14.1
  - griddataformats=1.0.2
  - gsd=4.2.0
  - h5py=3.15.1
  - hdf4=4.2.15
  - hdf5=1.14.6
  - importlib-metadata=8.7.0
  - itsdangerous=2.2.0
  - jax=0.7.2
  - jaxlib=0.7.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20250512.1
  - libaec=1.1.4
  - libblas=3.9.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.9.0
  - libcublas=12.9.1.4
  - libcublas-dev=12.9.1.4
  - libcudnn=9.10.1.4
  - libcudnn-dev=9.10.1.4
  - libcufft=11.4.1.4
  - libcufft-dev=11.4.1.4
  - libcurand=10.3.10.19
  - libcurand-dev=10.3.10.19
  - libcurl=8.16.0
  - libcusolver=11.7.5.82
  - libcusolver-dev=11.7.5.82
  - libcusparse=12.5.10.65
  - libcusparse-dev=12.5.10.65
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libgrpc=1.73.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libnetcdf=4.9.3
  - libnghttp2=1.67.0
  - libnvjitlink=12.9.86
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libprotobuf=6.31.1
  - libre2-11=2025.08.12
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libuuid=2.41.2
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzip=1.11.2
  - libzlib=1.3.1
  - llvmlite=0.45.1
  - lz4-c=1.10.0
  - markupsafe=3.0.3
  - matplotlib-base=3.10.7
  - mda-xdrlib=0.2.0
  - mdanalysis=2.10.0
  - mdtraj=1.11.0
  - ml_dtypes=0.5.1
  - mmtf-python=1.1.3
  - mpiplus=v0.0.2
  - mrcfile=1.5.4
  - msgpack-python=1.1.2
  - munkres=1.1.4
  - nccl=2.28.7.1
  - ncurses=6.5
  - netcdf4=1.7.3
  - networkx=3.5
  - nomkl=1.0
  - numba=0.62.1
  - numexpr=2.14.1
  - numpy=2.3.4
  - ocl-icd=2.3.3
  - ocl-icd-system=1.0.0
  - opencl-headers=2025.06.13
  - openjpeg=2.5.4
  - openmm=8.3.1
  - openmm-setup=1.6.1
  - openmmtools=0.25.3
  - openssl=3.5.4
  - opt_einsum=3.4.0
  - packaging=25.0
  - pandas=2.3.3
  - patsy=1.0.2
  - pdbfixer=1.11
  - pillow=12.0.0
  - pip=25.2
  - pthread-stubs=0.4
  - py-cpuinfo=9.0.0
  - pyedr=0.8.0
  - pymbar=4.2.0
  - pymbar-core=4.2.0
  - pyparsing=3.2.5
  - pytables=3.10.2
  - python=3.13.9
  - python-dateutil=2.9.0.post0
  - python-gil=3.13.9
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytng=0.3.4
  - pytz=2025.2
  - pyyaml=6.0.3
  - qhull=2020.2
  - re2=2025.08.12
  - readline=8.2
  - scikit-learn=1.7.2
  - scipy=1.16.3
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.2
  - statsmodels=0.14.5
  - threadpoolctl=3.6.0
  - tidynamics=1.1.2
  - tk=8.6.13
  - tqdm=4.67.1
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - werkzeug=3.1.3
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.2.5
  - zstd=1.5.7
prefix: /home/siida/miniforge3/envs/openmm
